
FROM       ubuntu:16.10

EXPOSE 27017

RUN apt-get update && apt-get install -y mongodb-server build-essentials

RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
